# Generated by Django 3.2.8 on 2021-10-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=264, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_users', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websites_searched', models.CharField(max_length=264, unique=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.users')),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Access_Record',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='webpage',
        ),
        migrations.AddField(
            model_name='records',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.website'),
        ),
    ]
