# Generated by Django 3.2.8 on 2021-10-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20211030_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('url', models.URLField(unique=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='relation',
        ),
        migrations.DeleteModel(
            name='records',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='website',
        ),
        migrations.AddField(
            model_name='access_record',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.webpage'),
        ),
    ]
