# Generated by Django 3.2.8 on 2021-11-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20211115_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('url', models.URLField(unique=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.topic')),
            ],
        ),
        migrations.AlterField(
            model_name='access_record',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.webpage'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
